"""Create parcel and parcel_type

Revision ID: a618039ce6ad
Revises:
Create Date: 2025-05-01 06:44:13.149868

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a618039ce6ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parcels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("parcel_type_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_currency", sa.String(length=3), nullable=False),
        sa.Column("delivery_price", sa.Float(), nullable=True),
        sa.Column("delivery_currency", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["parcel_type_id"],
            ["parcel_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parcels_user_id"), "parcels", ["user_id"], unique=False
    )

    parcel_types_table = sa.table(
        "parcel_types",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
    )

    op.bulk_insert(
        parcel_types_table,
        [
            {"id": 1, "name": "Clothing"},
            {"id": 2, "name": "Electronics"},
            {"id": 3, "name": "Other"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcels_user_id"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_table("parcel_types")
    # ### end Alembic commands ###
